from __future__ import annotations

from typing import Final


DSL_VERSION: Final[str] = "dui-lang/1.0"
MAX_NODES_PER_DOCUMENT: Final[int] = 400
MAX_CHILDREN_PER_NODE: Final[int] = 64
MAX_DEPTH_PER_DOCUMENT: Final[int] = 16
MAX_ACTIONS_PER_NODE: Final[int] = 12
MAX_BINDINGS_PER_DOCUMENT: Final[int] = 120


NODE_TYPE_ALLOWLIST: Final[set[str]] = {
    # 13.1 Layout and structure (24)
    "layout.surface",
    "layout.page",
    "layout.region",
    "layout.container",
    "layout.stack",
    "layout.inline",
    "layout.grid",
    "layout.columns",
    "layout.split",
    "layout.tabs",
    "layout.accordion",
    "layout.drawer",
    "layout.sidebar",
    "layout.section",
    "layout.card",
    "layout.panel",
    "layout.list",
    "layout.list_item",
    "layout.table",
    "layout.table_row",
    "layout.table_cell",
    "layout.timeline",
    "layout.carousel",
    "layout.portal_anchor",
    # 13.2 Content and typography (20)
    "content.heading",
    "content.text",
    "content.caption",
    "content.label",
    "content.code_block",
    "content.math_inline",
    "content.math_block",
    "content.markdown",
    "content.rich_text",
    "content.quote",
    "content.divider",
    "content.badge",
    "content.chip",
    "content.avatar",
    "content.icon",
    "content.image",
    "content.video",
    "content.audio",
    "content.kbd",
    "content.tag",
    # 13.3 Navigation (14)
    "nav.app_bar",
    "nav.breadcrumbs",
    "nav.nav_rail",
    "nav.nav_drawer",
    "nav.tab_bar",
    "nav.pager",
    "nav.stepper",
    "nav.link",
    "nav.button",
    "nav.icon_button",
    "nav.segmented",
    "nav.command_palette",
    "nav.search_bar",
    "nav.back_button",
    # 13.4 Forms and input (26)
    "form.form",
    "form.fieldset",
    "form.input_text",
    "form.input_password",
    "form.input_email",
    "form.input_phone",
    "form.input_number",
    "form.textarea",
    "form.select",
    "form.multiselect",
    "form.radio_group",
    "form.checkbox",
    "form.switch",
    "form.slider",
    "form.range_slider",
    "form.date_picker",
    "form.time_picker",
    "form.datetime_picker",
    "form.file_upload",
    "form.color_picker",
    "form.tag_input",
    "form.rating",
    "form.matrix_input",
    "form.math_expression",
    "form.code_input",
    "form.form_error_summary",
    # 13.5 Data and states (20)
    "data.kpi_card",
    "data.stat_group",
    "data.progress_bar",
    "data.progress_circle",
    "data.skeleton",
    "data.empty_state",
    "data.error_state",
    "data.info_callout",
    "data.warning_callout",
    "data.success_callout",
    "data.activity_feed",
    "data.log_view",
    "data.key_value",
    "data.property_list",
    "data.data_table",
    "data.pivot_table",
    "data.calendar",
    "data.agenda",
    "data.kanban_board",
    "data.tree_view",
    # 13.6 Charts and analytics (16)
    "chart.line",
    "chart.area",
    "chart.bar",
    "chart.stacked_bar",
    "chart.pie",
    "chart.donut",
    "chart.scatter",
    "chart.bubble",
    "chart.heatmap",
    "chart.radar",
    "chart.histogram",
    "chart.boxplot",
    "chart.sparkline",
    "chart.gauge",
    "chart.funnel",
    "chart.waterfall",
    # 13.7 Overlay and feedback (12)
    "overlay.modal",
    "overlay.dialog_confirm",
    "overlay.popover",
    "overlay.tooltip",
    "overlay.toast",
    "overlay.snackbar",
    "overlay.context_menu",
    "overlay.command_menu",
    "overlay.loading_overlay",
    "overlay.spotlight_tour",
    "overlay.bottom_sheet",
    "overlay.fullscreen_panel",
    # 13.8 Agent controls (10)
    "agent.prompt_box",
    "agent.patch_diff_view",
    "agent.patch_preview_toggle",
    "agent.revision_timeline",
    "agent.approval_panel",
    "agent.policy_violations",
    "agent.tool_call_log",
    "agent.surface_switcher",
    "agent.mode_switcher",
    "agent.capability_browser",
    # 13.9 LMS/math domain widgets (18)
    "lms.lesson_card",
    "lms.lesson_objectives",
    "lms.theory_points",
    "lms.exercise_list",
    "lms.exercise_card",
    "lms.answer_input",
    "lms.hint_panel",
    "lms.solution_panel",
    "lms.formula_sheet",
    "lms.topic_mastery_map",
    "lms.weak_topics_list",
    "lms.practice_queue",
    "lms.study_streak",
    "lms.assignment_calendar",
    "lms.focus_timer",
    "lms.quiz_block",
    "lms.flashcard_deck",
    "lms.mistake_review",
}


ACTION_TYPE_ALLOWLIST: Final[set[str]] = {
    "nav.open_route",
    "nav.open_surface",
    "state.set",
    "state.toggle",
    "ui.open_modal",
    "ui.close_modal",
    "ui.toast",
    "dui.request_patch",
    "dui.commit_patch",
    "dui.revert_revision",
    "capability.invoke",
}


THEME_TOKEN_ALLOWLIST: Final[set[str]] = {
    "bg",
    "surface",
    "surface_container",
    "text",
    "muted",
    "accent",
    "accent_container",
    "outline",
    "radius",
    "shadow",
    "font",
    "gap",
    "padding",
    "row_height",
    "focus_ring",
    "danger",
    "warning",
    "success",
    "info",
}


ZONE_ALLOWLIST: Final[set[str]] = {"header", "sidebar", "content", "footer"}


# Component types that can be lowered into current UiManifest widgets.
WIDGET_COMPILATION_MAP: Final[dict[str, dict[str, str]]] = {
    "data.kpi_card": {"kind": "kpi", "capability_id": "math.progress_overview"},
    "data.data_table": {"kind": "table", "capability_id": "math.learning_path"},
    "data.activity_feed": {"kind": "activity", "capability_id": "math.practice_queue"},
    "chart.line": {"kind": "chart", "capability_id": "math.mastery_trend"},
    "chart.bar": {"kind": "chart", "capability_id": "math.mastery_trend"},
    "chart.area": {"kind": "chart", "capability_id": "math.mastery_trend"},
    "layout.card": {"kind": "card", "capability_id": "ui.static.card"},
    "layout.list": {"kind": "list", "capability_id": "ui.static.list"},
    "layout.panel": {"kind": "panel", "capability_id": "ui.static.panel"},
    "layout.tabs": {"kind": "tabs", "capability_id": "ui.static.tabs"},
    "form.form": {"kind": "form", "capability_id": "ui.form.generic"},
    "lms.weak_topics_list": {"kind": "list", "capability_id": "math.weak_topics"},
    "lms.practice_queue": {"kind": "activity", "capability_id": "math.practice_queue"},
    "lms.study_streak": {"kind": "kpi", "capability_id": "math.study_streak"},
    "lms.assignment_calendar": {"kind": "table", "capability_id": "math.assignments"},
    "lms.focus_timer": {"kind": "panel", "capability_id": "math.focus_timer"},
    "lms.formula_sheet": {"kind": "card", "capability_id": "math.formulas"},
    "lms.topic_mastery_map": {"kind": "chart", "capability_id": "math.topic_mastery"},
    "lms.lesson_objectives": {"kind": "list", "capability_id": "math.lesson_objectives"},
    "lms.theory_points": {"kind": "card", "capability_id": "math.lesson_theory"},
    "lms.exercise_list": {"kind": "activity", "capability_id": "math.lesson_exercises"},
    "lms.quiz_block": {"kind": "form", "capability_id": "math.quiz"},
    "lms.flashcard_deck": {"kind": "card", "capability_id": "math.flashcards"},
    "lms.mistake_review": {"kind": "table", "capability_id": "math.mistakes"},
}


def is_allowed_node_type(node_type: str) -> bool:
    return node_type in NODE_TYPE_ALLOWLIST


def is_allowed_action_type(action_type: str) -> bool:
    return action_type in ACTION_TYPE_ALLOWLIST

